In [1]:
import numpy as np
from past.builtins import xrange
from cmath import e

def crout(A):
    n = len(A)
    L = [[0] * n for i in xrange(n)]
    U = [[0] * n for i in xrange(n)]
    for j in xrange(n):
        U[j][j] = 1
        for i in xrange(j, n):
            alpha = float(A[i][j])
            for k in xrange(j):
                alpha -= L[i][k]*U[k][j]
            L[i][j] = alpha
        for i in xrange(j+1, n):
            tempU = float(A[j][i])
            for k in xrange(j):
                tempU -= L[j][k]*U[k][i]
            if int(L[j][j]) == 0:
                L[j][j] = e-40
            U[j][i] = tempU/L[j][j]
    return L, U




def C(A,B):

    C = np.zeros((3, 4))


    for i in range(0,3,1):
        for j in range(0,4,1):
          if j==3:
            C[i,j]=B[0][i]
          else:
            C[i,j]=A[i,j]

    return C




A = np.array([[-6, 3,-4,-3], [ 4,-7,-3, 2], [ 6,-8, 4, 4],[ 7,-1, 3,-1]])

b1 = np.array([[-35, 10,50,25]])
b2 = np.array([[(1/2), (5/4),-2,2]])
b3 = np.array([[-2, -32,-6,10]])

LU = crout(A)

C1 = C(A,b1)
C2 = C(A,b2)
C3 = C(A,b3)

print("A Value")
print(A)

print("L Value")
print(LU[0])

print("U Value")
print(LU[1])

print("C1 Value")
print(C1)

print("C2 Value")
print(C2)

print("C3 Value")
print(C3)



A Value
[[-6  3 -4 -3]
 [ 4 -7 -3  2]
 [ 6 -8  4  4]
 [ 7 -1  3 -1]]
L Value
[[-6.0, 0, 0, 0], [4.0, -5.0, 0, 0], [6.0, -5.0, 5.666666666666666, 0], [7.0, 2.5, -4.499999999999999, -3.7058823529411766]]
U Value
[[1, -0.5, 0.6666666666666666, 0.5], [0, 1, 1.1333333333333333, -0.0], [0, 0, 1, 0.17647058823529413], [0, 0, 0, 1]]
C1 Value
[[ -6.   3.  -4. -35.]
 [  4.  -7.  -3.  10.]
 [  6.  -8.   4.  50.]]
C2 Value
[[-6.    3.   -4.    0.5 ]
 [ 4.   -7.   -3.    1.25]
 [ 6.   -8.    4.   -2.  ]]
C3 Value
[[ -6.   3.  -4.  -2.]
 [  4.  -7.  -3. -32.]
 [  6.  -8.   4.  -6.]]


In [4]:
import numpy as np

A = np.matrix([[-6, 3,-4,-3], [ 4,-7,-3, 2], [ 6,-8, 4, 4],[ 7,-1, 3,-1]])

b1 = np.matrix([[-35], [10],[50],[25]])
b2 = np.matrix([[(1/2)], [(5/4)],[-2],[2]])
b3 = np.matrix([[-2],[-32],[-6],[10]])

Xb1 = A**(-1)*b1
Xb2 = A**(-1)*b2
Xb3 = A**(-1)*b3

print("El resultado de X es:",Xb1)
print("El resultado de X es:",Xb2)
print("El resultado de X es:",Xb3)

#To verify the result, X*A is calculated and it must give B
#print("The result of A*X is B -> ", A * Xb3)

El resultado de X es: [[ 1.00000000e+00]
 [-3.00000000e+00]
 [ 5.00000000e+00]
 [-1.77635684e-15]]
El resultado de X es: [[ 0.5 ]
 [ 0.25]
 [-0.5 ]
 [-0.25]]
El resultado de X es: [[-1.]
 [ 1.]
 [ 5.]
 [-3.]]
